name: "Terraform Deploy"
on:
  push:
    branches:
      - main

permissions:
  id-token: write
  # issuer: write
  # pull-request: write
  contents: read

jobs:
  terraform:
    name: "Terraform"
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@master

      - name: "Setup Terraform"
        uses: hashicorp/setup-terraform@v2

      - name: "Az CLI login"
        uses: azure/login@v1
        with:
          client-id: ${{secrets.AZURE_CLIENT_ID}}
          tenant-id: ${{secrets.AZURE_TENANT_ID}}
          subscription-id: ${{secrets.AZURE_SUBSCRIPTION_ID}}

      - name: "Az account"
        run: az account show

      - name: "cd to IaC dir"
        run: cd IaC

      - name: "pwd"
        run: pwd

      - name: "Terraform Init"
        id: init
        env:
          STORAGE_ACCOUNT: ${{ secrets.STATE_STORAGE_ACCOUNT }}
          CONTAINER_NAME: ${{ secrets.STATE_CONTAINER_NAME }}
          RESOURCE_GROUP_NAME: ${{ secrets.STATE_RESOURCE_GROUP_NAME }}
          ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
          ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
        run: terraform init -backend-config="storage_account_name=$STORAGE_ACCOUNT" -backend-config="container_name=$CONTAINER_NAME" -backend-config="resource_group_name=$RESOURCE_GROUP_NAME"
      - name: "Terraform Format"
        id: fmt
        run: terraform fmt

      - name: "Terraform Validate"
        id: validate
        run: terraform validate -no-color

      - name: "Terraform Plan"
        id: plan
        env:
          TF_VAR_agent_client_id: ${{ secrets.TF_VAR_agent_client_id }}
          TF_VAR_agent_client_secret: ${{ secrets.TF_VAR_agent_client_secret }}
          TF_VAR_subscription_id: ${{ secrets.TF_VAR_subscription_id }}
          TF_VAR_tenant_id: ${{ secrets.TF_VAR_tenant_id }}
        run: terraform plan -no-color -var-file ../lab.auto.tfvars # uses subscription id from the env

      - name: "Terraform Apply"
        id: apply
        env:
          TF_VAR_agent_client_id: ${{ secrets.TF_VAR_agent_client_id }}
          TF_VAR_agent_client_secret: ${{ secrets.TF_VAR_agent_client_secret }}
          TF_VAR_subscription_id: ${{ secrets.TF_VAR_subscription_id }}
          TF_VAR_tenant_id: ${{ secrets.TF_VAR_tenant_id }}
        run: terraform apply -var-file ../lab.auto.tfvars # uses subscription id from the env